# Generated by Django 5.1 on 2024-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interceptor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('files', models.JSONField(default=list)),
                ('edited_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
